/*
 * File: app/view/Container.js
 * Date: Mon Nov 21 2011 02:21:53 GMT-0600 (Central Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Agile.view.Container', {
	extend: 'Agile.view.ui.Container',

	initComponent: function() {
		var me = this;
		me.callParent(arguments);
	}
});