/*
 * File: app/view/MyWindow.js
 * Date: Tue Nov 22 2011 23:46:28 GMT-0600 (Central Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Agile.view.MyWindow', {
	extend: 'Agile.view.ui.MyWindow',

	initComponent: function() {
		var me = this;
		me.callParent(arguments);
	}
});