/*
 * File: app/view/ui/Container.js
 * Date: Wed Nov 23 2011 02:40:28 GMT-0600 (Central Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

var arrItems = [];

var objViewMenu;

var objLangs = editAreaLoader.syntax_display_name;

for (var strKey in objLangs) {
	
	var strLang = objLangs[strKey];
	
	var objItem = {
		xtype: 'menucheckitem',
		text: strLang,
		checked: ( (strLang == "PHP") ? true : false ),
		group: 'language',
		file: strKey,
		handler: function() { editAreaLoader.execCommand('editor','change_syntax', this.file) }
		
	}
	
	arrItems.push(objItem);
	
}

objViewMenu =  {
				xtype: 'menu',
				id: 'menu_view',
				items: [
					{
						xtype: 'menuitem',
						id: 'syntax',
						iconCls: 'syntax',
						text: 'Syntax',
						menu: {
							xtype: 'menu',
							id: 'menu_syntax',
							items: arrItems
						}
					},
					{
						xtype: 'menuseparator',
						id: 'sep7'
					},
					{
						xtype: 'menucheckitem',
						id: 'highlight',
						iconCls: 'highlight',
						text: 'Highlighting',
						checked: true
					},
					{
						xtype: 'menucheckitem',
						id: 'lines',
						iconCls: 'lines',
						text: 'Line Numbers',
						checked: true
					},
					{
						xtype: 'menucheckitem',
						id: 'wrap',
						iconCls: 'wrap',
						text: 'Word Wrap'
					}
				]
			};


Ext.define('Agile.view.ui.Container', {
	extend: 'Ext.container.Container',

	style: 'height: 95%; width: 100%;',
	layout: {
		type: 'anchor'
	},
	
	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'toolbar',
					id: 'toolbar',
					items: [
						{
							xtype: 'button',
							border: '',
							id: 'btn_file',
							text: 'File',
							menu: {
								xtype: 'menu',
								id: 'menu_file',
								items: [
									{
										xtype: 'menuitem',
										id: 'new',
										itemId: '',
										iconCls: 'new',
										text: 'New'
									},
									{
										xtype: 'menuitem',
										id: 'open',
										itemId: '',
										iconCls: 'open',
										text: 'Open'
									},
									{
										xtype: 'menuitem',
										id: 'open_recent',
										itemId: '',
										iconCls: 'open_recent',
										text: 'Open Recent',
										menu: {
											xtype: 'menu',
											id: 'recent_menu',
											title: '',
											items: [
												{
													xtype: 'menuitem',
													text: 'C:\\1.txt'
												},
												{
													xtype: 'menuitem',
													text: 'C:\\2.txt'
												},
												{
													xtype: 'menuitem',
													text: 'C:\\3.txt'
												}
											]
										}
									},
									{
										xtype: 'menuitem',
										id: 'close',
										itemId: '',
										iconCls: 'close',
										text: 'Close'
									},
									{
										xtype: 'menuitem',
										id: 'close_all',
										itemId: '',
										iconCls: 'close_all',
										text: 'Close All'
									},
									{
										xtype: 'menuseparator',
										id: 'sep1'
									},
									{
										xtype: 'menuitem',
										id: 'save',
										itemId: '',
										iconCls: 'save',
										text: 'Save'
									},
									{
										xtype: 'menuitem',
										id: 'save_all',
										itemId: '',
										iconCls: 'save_all',
										text: 'Save All'
									},
									{
										xtype: 'menuseparator',
										id: 'sep2'
									},
									{
										xtype: 'menuitem',
										id: 'exit',
										itemId: '',
										iconCls: 'exit',
										text: 'Exit'
									}
								]
							}
						},
						{
							xtype: 'button',
							id: 'btn_edit',
							text: 'Edit',
							menu: {
								xtype: 'menu',
								id: 'menu_edit',
								items: [
									{
										xtype: 'menuitem',
										id: 'undo',
										iconCls: 'undo',
										text: 'Undo'
									},
									{
										xtype: 'menuitem',
										id: 'redo',
										iconCls: 'redo',
										text: 'Redo'
									},
									{
										xtype: 'menuseparator',
										id: 'sep3'
									},
									{
										xtype: 'menuitem',
										id: 'cut',
										iconCls: 'cut',
										text: 'Cut'
									},
									{
										xtype: 'menuitem',
										id: 'copy',
										iconCls: 'copy',
										text: 'Copy'
									},
									{
										xtype: 'menuitem',
										id: 'paste',
										iconCls: 'paste',
										text: 'Paste'
									},
									{
										xtype: 'menuseparator',
										id: 'sep4'
									},
									{
										xtype: 'menuitem',
										id: 'insert',
										iconCls: 'insert',
										text: 'Insert',
										menu: {
											xtype: 'menu',
											id: 'menu_insert',
											items: [
												{
													xtype: 'menuitem',
													id: 'color_code',
													iconCls: 'color_code',
													text: 'Color Code',
													menu: {
														xtype: 'colormenu',
														id: 'menu_color'
													}
												}
											]
										}
									},
									{
										xtype: 'menuseparator',
										id: 'sep5'
									},
									{
										xtype: 'menuitem',
										id: 'prj_settings',
										iconCls: 'prj_settings',
										text: 'Project Settings'
									},
									{
										xtype: 'menuseparator',
										id: 'sep6'
									},
									{
										xtype: 'menuitem',
										id: 'edt_options',
										iconCls: 'edt_options',
										text: 'Editor Options'
									}
								]
							}
						},
						{
							xtype: 'button',
							id: 'btn_view',
							enableToggle: true,
							text: 'View',
							menu: objViewMenu
						},
						{
							xtype: 'button',
							id: 'btn_help',
							text: 'Help',
							menu: {
								xtype: 'menu',
								id: 'menu_help',
								items: [
									{
										xtype: 'menuitem',
										id: 'about',
										iconCls: 'about',
										text: 'About'
									}
								]
							}
						}
					]
				},
				{
					xtype: 'textareafield',
					id: 'editor',
					fieldLabel: '',
					hideLabel: true,
					anchor: '100% 0%'
				}
			]
		});
				
		me.callParent(arguments);
		
		
	}
});