/*
 * File: app/view/ui/MyWindow.js
 * Date: Wed Nov 23 2011 00:07:18 GMT-0600 (Central Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Glide.view.ui.MyWindow', {
	extend: 'Ext.window.Window',

	height: 250,
	width: 400,
	resizable: false,
	layout: {
		type: 'fit'
	},
	title: 'My Window',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'panel',
					title: ''
				}
			]
		});

		me.callParent(arguments);
	}
});